// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQG66NM3tq_p45_82iHPc5eoD_EfEE8u8',
    appId: '1:571545800069:web:9903f66d1eb2ead92ec8ec',
    messagingSenderId: '571545800069',
    projectId: 'i-shal-maxi',
    authDomain: 'i-shal-maxi.firebaseapp.com',
    storageBucket: 'i-shal-maxi.firebasestorage.app',
    measurementId: 'G-LDLGD3CW04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK-QxxIjWcnS2zyKHNcjXxCO8dyBYinB0',
    appId: '1:571545800069:android:97037020dc67387b2ec8ec',
    messagingSenderId: '571545800069',
    projectId: 'i-shal-maxi',
    storageBucket: 'i-shal-maxi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBflxAJkTxs3fin8C6WtF81d4MNb4JBEeo',
    appId: '1:571545800069:ios:e2528dcf406baddd2ec8ec',
    messagingSenderId: '571545800069',
    projectId: 'i-shal-maxi',
    storageBucket: 'i-shal-maxi.firebasestorage.app',
    iosClientId: '571545800069-166rl89aqv484du4ja1m1k6c08ip15a7.apps.googleusercontent.com',
    iosBundleId: 'com.example.myHealth',
  );
}
